=== JoeBengalen/private-tables/raml/schema/fields.json
{
    "$schema": "http: \/\/json-schema.org\/draft-04\/schema#",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "id": {
                "type": "integer"
            },
            "tableId": {
                "type": "integer"
            },
            "name": {
                "type": "string"
            },
            "type": {
                "type": "string"
            },
            "length": {
                "type": [
                    "integer",
                    "null"
                ]
            },
            "allowNull": {
                "type": "boolean"
            },
            "default": {
                "type": [
                    "string",
                    "null"
                ]
            },
            "comment": {
                "type": [
                    "string",
                    "null"
                ]
            },
            "isPrimaryKey": {
                "type": "boolean"
            },
            "autoIncrement": {
                "type": "boolean"
            }
        },
        "required": [
            "id",
            "tableId",
            "name",
            "type",
            "length",
            "allowNull",
            "default",
            "comment",
            "isPrimaryKey",
            "autoIncrement"
        ]
    }
}

=== JoeBengalen/private-tables/raml/sample/fields.json
[
    {
        "id": 1,
        "tableId": 1,
        "name": "id",
        "type": "INTEGER",
        "length": null,
        "allowNull": false,
        "default": null,
        "comment": null,
        "isPrimaryKey": false,
        "autoIncrement": false
    },
    {
        "id": 2,
        "tableId": 1,
        "name": "fieldname",
        "type": "STRING",
        "length": 255,
        "allowNull": false,
        "default": null,
        "comment": null,
        "isPrimaryKey": false,
        "autoIncrement": false
    }
]
